name: Publish to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: 19

      - run: npm i
      - run: npm run build
      - name: Disable jekyll
        run: touch build/.nojekyll
      
      - name: Create pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: "./build"
          retention-days: "14"
    
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${steps.deployment.outputs.page_url}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1